# Generated by Django 3.0.4 on 2020-07-17 17:19

from django.db import migrations, models
import django.db.models.deletion
import genki.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', genki.models.DiscordIDField(db_index=True, help_text="The Guild's Discord ID.", primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoleTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text="The Role's name.", max_length=100)),
                ('colour', genki.models.HexColourField(help_text="The Role's colour in hex.")),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('name', models.CharField(db_index=True, help_text="The Series' name.", max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name_plural': 'series',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', genki.models.DiscordIDField(db_index=True, help_text="The User's Discord ID.", primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('name', models.CharField(db_index=True, help_text="The Game's name.", max_length=255, primary_key=True, serialize=False, unique=True)),
                ('completion_role', models.OneToOneField(help_text='The role to grant upon game completion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game', to='playthrough.RoleTemplate')),
                ('prequels', models.ManyToManyField(blank=True, help_text="The game's prequels.", related_name='sequels', to='playthrough.Game')),
                ('series', models.ForeignKey(help_text='The Series the Game belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='games', to='playthrough.Series')),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', genki.models.DiscordIDField(db_index=True, help_text="The Channel's Discord ID.", primary_key=True, serialize=False, unique=True)),
                ('game', models.ForeignKey(help_text='The Game the Channel is for.', on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='playthrough.Game')),
                ('guild', models.ForeignKey(help_text='The Guild the Channel is in.', on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='playthrough.Guild')),
                ('owner', models.ForeignKey(help_text='The owner of the Channel.', on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='playthrough.User')),
            ],
        ),
    ]
