# Generated by Django 3.0.4 on 2020-05-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playthrough', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guild',
            name='name',
        ),
        migrations.AlterField(
            model_name='guild',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
