# Generated by Django 3.0.4 on 2020-07-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playthrough', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='admins',
            field=models.ManyToManyField(help_text="The Guild's bot admins.", related_name='admin_for', to='playthrough.User'),
        ),
    ]
