# Generated by Django 3.1.2 on 2020-10-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playthrough', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='finished',
            field=models.BooleanField(default=False, help_text='Whether or not the user finished playing the game.'),
        ),
    ]
