# Generated by Django 3.1.2 on 2020-10-11 16:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('playthrough', '0002_channel_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The time the archive was created.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='archive',
            name='channel',
            field=models.ForeignKey(help_text='The Channel the archive is for.', on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='playthrough.channel'),
        ),
    ]
