# Generated by Django 3.0.4 on 2020-07-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playthrough', '0002_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(blank=True, help_text="The Game's slug. Auto-generated.", unique=True),
        ),
        migrations.AddField(
            model_name='series',
            name='slug',
            field=models.SlugField(blank=True, help_text="The Series' slug. Auto-generated.", unique=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(db_index=True, help_text="The Series' name.", max_length=255),
        ),
    ]
