# Generated by Django 3.0.4 on 2020-07-17 21:06

from django.db import migrations, models
import django.db.models.deletion
import genki.models


class Migration(migrations.Migration):

    dependencies = [
        ('playthrough', '0002_guild_admins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', genki.models.DiscordIDField(db_index=True, help_text="The Category's Discord ID.", primary_key=True, serialize=False, unique=True)),
                ('guild', models.ForeignKey(help_text="The Category's Guild.", on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='playthrough.Guild')),
            ],
        ),
        migrations.CreateModel(
            name='GameConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_role_id', genki.models.DiscordIDField(help_text='The ID of the Role to grant upon game completion.')),
                ('category', models.ForeignKey(help_text='The Category for active channels.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='playthrough.Category')),
                ('game', models.ForeignKey(help_text='The Game to configure.', on_delete=django.db.models.deletion.CASCADE, related_name='configred_with', to='playthrough.Game')),
                ('guild', models.ForeignKey(help_text='The Guild to configure for.', on_delete=django.db.models.deletion.CASCADE, related_name='games', to='playthrough.Guild')),
            ],
        ),
    ]
