# Generated by Django 3.0.4 on 2020-07-15 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playthrough', '0002_auto_20200521_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('name', models.CharField(db_index=True, help_text="The Series' name in English.", max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name_plural': 'series',
            },
        ),
        migrations.AlterField(
            model_name='guild',
            name='id',
            field=models.CharField(db_index=True, help_text="The Guild's Discord ID.", max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('name', models.CharField(db_index=True, help_text="The Game's name in English.", max_length=255, primary_key=True, serialize=False, unique=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='playthrough.Series')),
            ],
        ),
    ]
