# Generated by Django 3.1.2 on 2020-10-11 19:46

from django.db import migrations, models
import django.db.models.deletion
import genki.models


class Migration(migrations.Migration):

    dependencies = [
        ('playthrough', '0003_auto_20201011_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaRoleConfig',
            fields=[
                ('roletemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='playthrough.roletemplate')),
                ('expression', models.CharField(help_text="The meta role's expression.", max_length=255)),
                ('role_id', genki.models.DiscordIDField(db_index=True, help_text="The Meta Role's ID on Discord.", unique=True)),
                ('games', models.ManyToManyField(help_text='The configured Games the MetaRole is associated with.', related_name='meta_roles', to='playthrough.GameConfig')),
            ],
            bases=('playthrough.roletemplate',),
        ),
        migrations.DeleteModel(
            name='MetaRoleTemplate',
        ),
    ]
