# Generated by Django 3.0.4 on 2020-07-17 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playthrough', '0003_category_gameconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='series',
            field=models.ForeignKey(help_text='The Series the Game belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='playthrough.Series'),
        ),
    ]
