# Generated by Django 3.0.4 on 2020-07-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playthrough', '0003_auto_20200715_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='prequels',
            field=models.ManyToManyField(blank=True, related_name='_game_prequels_+', to='playthrough.Game'),
        ),
    ]
