# Generated by Django 3.0.4 on 2020-07-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playthrough', '0004_game_prequels'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text="The role's name in English.", max_length=100)),
                ('colour', models.CharField(help_text="The role's colour in hex.", max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='prequels',
            field=models.ManyToManyField(blank=True, related_name='sequels', to='playthrough.Game'),
        ),
    ]
