# Generated by Django 3.1.2 on 2020-10-11 21:26

from django.db import migrations
import genki.models


class Migration(migrations.Migration):

    dependencies = [
        ('playthrough', '0004_auto_20201011_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaroleconfig',
            name='guild',
            field=genki.models.DiscordIDField(default='', help_text="The Meta Role's Guild ID on Discord."),
            preserve_default=False,
        ),
    ]
