# Generated by Django 3.1.2 on 2020-10-11 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playthrough', '0005_metaroleconfig_guild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metaroleconfig',
            name='guild',
            field=models.ForeignKey(help_text='The Guild to configure for.', on_delete=django.db.models.deletion.CASCADE, related_name='meta_roles', to='playthrough.guild'),
        ),
    ]
