# Generated by Django 3.1.2 on 2020-10-12 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playthrough', '0006_auto_20201011_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='playable',
            field=models.BooleanField(default=True, help_text='Whether or not users can create playthrough channels.'),
        ),
    ]
