# Generated by Django 3.1.2 on 2020-10-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playthrough', '0009_auto_20201014_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='playable',
        ),
        migrations.AddField(
            model_name='gameconfig',
            name='playable',
            field=models.BooleanField(default=True, help_text='Whether or not users can create playthrough channels.'),
        ),
    ]
