# Generated by Django 3.1.2 on 2020-10-18 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playthrough', '0010_auto_20201015_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='name',
            field=models.CharField(blank=True, help_text="The guild's name", max_length=255, null=True),
        ),
    ]
