version: '3'
services:
    genki:
        image: genki
        build:
            context: .
        volumes:
            - static:/vol/web/static
            - genki_media:/vol/web/media
        env_file:
            - .env
    nginx:
        build:
            context: ./deployment/nginx
        volumes:
            - static:/vol/static
            - genki_media:/vol/media
        ports:
            - "10080:8080"
        depends_on:
            - genki
volumes:
    static:
    genki_media:
        external: true
networks:
    default:
        driver: bridge
        driver_opts: 
            com.docker.network.bridge.name: genki
        ipam:
            driver: default
            config:
                - subnet: 172.30.0.0/16
