version: '3'
services:
    genki:
        image: genki
        restart: unless-stopped
        build:
            context: .
        volumes:
            - static:/vol/web/static
            - genki_media:/vol/web/media
        networks:
          - frau
          - internal
        env_file:
          - .env
        depends_on:
          - db
    db:
        image: postgres
        restart: unless-stopped
        volumes:
            - ./db:/var/lib/postgresql/data
        ports:
            - 10090:5432
        env_file:
          - .env
        networks:
            - frau
    nginx:
        restart: unless-stopped
        build:
            context: ./deployment/nginx
        volumes:
            - static:/vol/static
            - genki_media:/vol/media
        ports:
            - "10080:8080"
        depends_on:
            - genki
        networks:
            - internal
volumes:
    static:
    genki_media:
        external: true
networks:
    internal:
    frau:
        driver: bridge
